### ISSUE TITLE
weird results for depth map input

### ISSUE THREAD

**Issue by l1346792580123** [autonomousvision/shape_as_points#10]
I use SAP to reconstruct mesh from depth map input, while the result is somekind weird. It seems that SAP try to reconstruct closed shape. For those only one side oriented point clouds extracted from depth map SAP additionally generates some discrete faces. Is there any way to remove these faces?

**Comment by pengsongyou** [comment]
Poisson solver does the reconstruction globally based on the observations (depth map in your case), and it will close all the surface to form a watertight mesh. To handle the non-watertight scenario, it is a whole different research area. You can take a look at some recent work on non-signed distance field (NDF).
