### ISSUE TITLE
What is train_overfit.lst and test_overfit.lst?

### ISSUE THREAD

**Issue by Kitsunetic** [autonomousvision/shape_as_points#11]
Thank you for great work

I'm curious about what `train_overfit.lst` and `test_overfit.lst` mean in the preprocessed dataset which can be downloaded in [*Dataset for Learning-based Reconstruction*](https://github.com/autonomousvision/shape_as_points#dataset-for-learning-based-reconstruction)?

I cannot find any clue in `scripts/preprocess_shapenet.py`.

Thank you

**Comment by pengsongyou** [comment]
I think I forgot to delete those two files. It is not related to anything.
