### ISSUE TITLE
The question is about the model and training.

### ISSUE THREAD

**Issue by Siziff** [autonomousvision/shape_as_points#13]
Good afternoon, I have a few questions, I am trying to do a point cloud processing cycle for my master's work at the university and I will be very glad if you answer my questions:
1. From your article, I did not quite understand what exactly is being trained in the model, could you clarify which parameters are being improved in the learning process?
2. Do I understand correctly that you trained your model on all three datasets? I am trying to optimize a point cloud in the form of an airplane, and the result of your model does not turn out to be as high-quality as I would like. I want to train the model on 3D figures of planes, BUT there are already planes in the ShapeNet dataset on which you trained your model, and despite this, the result is still not very good (the result is attached to the cart). Does it make sense to retrain your model ONLY on airplanes to improve the result ?
The original number of points in the aircraft model is about 60000+-.

![image](https://user-images.githubusercontent.com/42972554/205590227-cd23a798-533d-4174-acdc-1b81f8ca71cb.png)
![image](https://user-images.githubusercontent.com/42972554/205590330-6ca7fd85-fa07-42f5-9943-86f24c424c98.png)

**Comment by pengsongyou** [comment]
Hi, I will reply to you below.

> Good afternoon, I have a few questions, I am trying to do a point cloud processing cycle for my master's work at the university and I will be very glad if you answer my questions:
> 
> 1. From your article, I did not quite understand what exactly is being trained in the model, could you clarify which parameters are being improved in the learning process?

We try to train the weight of a point network that produces the point positions and normals

> 2. Do I understand correctly that you trained your model on all three datasets? I am trying to optimize a point cloud in the form of an airplane, and the result of your model does not turn out to be as high-quality as I would like. I want to train the model on 3D figures of planes, BUT there are already planes in the ShapeNet dataset on which you trained your model, and despite this, the result is still not very good (the result is attached to the cart). Does it make sense to retrain your model ONLY on airplanes to improve the result ?
>    The original number of points in the aircraft model is about 60000+-.
> 
> ![image](https://user-images.githubusercontent.com/42972554/205590227-cd23a798-533d-4174-acdc-1b81f8ca71cb.png) ![image](https://user-images.githubusercontent.com/42972554/205590330-6ca7fd85-fa07-42f5-9943-86f24c424c98.png)


What do you mean by all three datasets? For our learning-based setting, we only train on the ShapeNet. We indeed consider 3 different noises, but we train them separately.

I guess you mix a bit our optimization-based and learning-based setting?
