### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Siziff** [autonomousvision/shape_as_points#14]
got error when trying to make parameter o3d_show as True in yaml file. 

aga/res_32 --train:lr_pcl 0.002000                                    --data:object_id -1
Changing model:grid_res ---- 256 to 32
Changing model:psr_sigma ---- 2 to 2
Changing train:input_mesh ----  to None
Changing train:total_epochs ---- 4000 to 1000
Changing train:out_dir ---- /dsk1/shape_as_points/after/aga to /dsk1/shape_as_points/after/aga/res_32
Changing train:lr_pcl ---- 2e-2 to 0.002000
Changing data:object_id ---- 0 to -1
/dsk1/shape_as_points/after/aga/res_32
Segmentation fault (core dumped)

Couldn't find the right solution to the questions, how can this be fixed?

**Comment by pengsongyou** [comment]
Have you tried to run with `o3d_show=True` on a machine without display? It only works on workstation/desktop, not on clusters or so without display.

**Comment by Siziff** [comment]
@pengsongyou  Thanks for the reply ^_^ But aren't there any ways to do this on a remote server? I tried to make a screen emulator, but it didn't help.

**Comment by pengsongyou** [comment]
I have not tried that myself. If you figure out a way, please let me know :)
