### ISSUE TITLE
help. run failed Use a pre-trained model

### ISSUE THREAD

**Issue by zuixiaosanlang** [autonomousvision/shape_as_points#15]
![image](https://user-images.githubusercontent.com/20105627/209902433-30fb6830-4b97-4d12-88a7-ef4f90526567.png)

but failed.

![image](https://user-images.githubusercontent.com/20105627/209902475-d595accb-1284-404e-99ab-1be686096359.png)

![image](https://user-images.githubusercontent.com/20105627/209902513-31e59d15-e53a-49f9-a777-46dbebad77ab.png)

i must download the shapenet dataset ????

**Comment by Polaris1010** [comment]
Have you solved this problem? I have encountered the same problem now. 
How did you solve it？
