### ISSUE TITLE
Is this method suitable for 3DScene? example,  a room

### ISSUE THREAD

**Issue by zuixiaosanlang** [autonomousvision/shape_as_points#16]
I try, but get a bad result.

**Comment by pengsongyou** [comment]
Hi,

We have not tried it, but I do not think it can work as well as our object-level reconstruction results. One main reason is the limited resolution of the indicator grid. Another reason is, for the learning-based pipeline, we only trained on the ShapeNet object, not indoor scene dataset like [this synthetic indoor scene dataset](https://github.com/autonomousvision/convolutional_occupancy_networks#synthetic-indoor-scene-dataset). If you can train on that, I believe you can have better results.

Best
Songyou
