### ISSUE TITLE
About the igl, ERROR: Could not find a version that satisfies the requirement igl (from versions: none)

### ISSUE THREAD

**Issue by liuyifan6613** [autonomousvision/shape_as_points#22]
ERROR: Could not find a version that satisfies the requirement igl (from versions: none)
ERROR: No matching distribution found for igl
igl cannot be installed by pip. How can I install igl?

**Comment by steven-mantis** [comment]
you can try pip install libigl.

**Comment by liuyifan6613** [comment]
> you can try pip install libigl.

I see. Thank you very much
