### ISSUE TITLE
Requiring to Downgrade Dependencies

### ISSUE THREAD

**Issue by EliCDavis** [autonomousvision/shape_as_points#26]
Following the setup guide, I had to downgrade numpy and pillow to get things to work.

# Numpy 

version that worked for me, bool is now depreciated

```
pip3 install numpy==1.23.1
```

# Pillow 

```
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

version that worked for me, _imaging issues referenced in this issue

```
conda install install pillow==9.0.0
```

**Comment by pengsongyou** [comment]
Thanks a lot for pointing this out. The repo has not been actively maintained, but I am glad to know that with a few modifications now it is still working after 3 years :)
