### ISSUE TITLE
Input all Points for Optimization-based method?

### ISSUE THREAD

**Issue by Runsong123** [autonomousvision/shape_as_points#3]
Hi Songyou,

Thanks for sharing your code for the excellent work! 
I am curious about the optimization-based part and I have two questions. Can you help me? thanks a lot in advance. :)

* Do you use the whole point cloud? For example,  the  "daratech" shape(SRB dataset) contains 71265 point cloud, you put all the point clouds for your methods or you downsample them first.
* Can you provide the parameter for Poisson Surface Reconstruction(e.g. depth) and parameter for minimum spanning tree method if possible.

Looking forward to your reply!

Best,
Runsong

**Comment by pengsongyou** [comment]
Hi @Runsong123 , thanks for your interest in our work. Regarding your questions:

- We use all points during the optimization, but only use the subsampled points for chamfer loss calculation in each iteration. Check [here](https://github.com/autonomousvision/shape_as_points/blob/main/configs/optim_based/dgp.yaml#L21) and [here](https://github.com/autonomousvision/shape_as_points/blob/12757682f1075d83738b52f96747463b77343caf/src/optimization.py#L126).
- For sPSR, we use depth=8. For minimum spanning tree algorithm, we use the [implementation](http://www.open3d.org/docs/0.7.0/python_api/open3d.geometry.estimate_normals.html) from Open3D. We set `search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)`.

Hope this helps.

Best,
Songyou

**Comment by Runsong123** [comment]
Got it! Thanks a lot!  :)

Best,
Runsong
