### ISSUE TITLE
question about rasterize function

### ISSUE THREAD

**Issue by l1346792580123** [autonomousvision/shape_as_points#4]
Thanks for sharing this great work!
I am a little confused about the rasterize function. It seems that the weight is the product of the absolute distance, and the value on the gird is the weighted sum of all the relevant points.  Does the grid value need to be normalized? Because I have found that when I  rasterize the parameters of the points to the grid, the value on the grid increases as the number of the sampled points increases. But when I normalize the value on the grid, there is an error of marching cube. Do you have any advice or is there any relationship between the number of sampling points and the grid size?

**Comment by pengsongyou** [comment]
Hi @l1346792580123 ,

Thanks for your interest in our work.

You are right, the grid values are indeed increasing with the number of points. Therefore, we also scale the output indicator grid value by dividing the value at grid position (0,0,0). Check [here](https://github.com/autonomousvision/shape_as_points/blob/main/src/dpsr.py#L61-L65). I am not sure how you normalize the grid value, but in our way, values inside the shape having the negative values and outside positive. We don't see any errors in marching cubes.

Best,
Songyou

**Comment by l1346792580123** [comment]
Thanks for your reply. I have found the error was caused by dividing by 0 during normalization, and now I can get the correct result.
