### ISSUE TITLE
Mesh Evaluation for the Optimization-based part

### ISSUE THREAD

**Issue by Runsong123** [autonomousvision/shape_as_points#5]
Hi Songyou,

Thanks again for sharing the code for your excellent work! 
I found that the script "eval_meshes.py" is prepared for the learning-based method, but I want to evaluate the mesh result produced by the optimization-based part. Could you please give some suggestions for this?

Looking for your reply. :)

Best,
Runsong

**Comment by pengsongyou** [comment]
Hi @Runsong123,

We use the same [MeshEvaluator](https://github.com/autonomousvision/shape_as_points/blob/main/src/eval.py#L23-L130) for evaluation of both optimization-based and learning-based methods.

For optimization-based method, you could try to adapt the following code:
```python
n_points=50000
evaluator=MeshEvaluator(n_points)

gt_cache={}

def evaluate_mesh(gt_path, es_path, n_points=50000, normalize=True):
    es_mesh = trimesh.load_mesh(es_path)
    gt_scale = 1.

    # sample from gt mesh
    if gt_path in gt_cache.keys():
        gt_pointcloud, gt_normals, gt_scale = gt_cache[gt_path]
    else:
        if os.path.splitext(gt_path)[-1]=='.xyz': # DGP dataset
            gt_pointcloud = np.loadtxt(gt_path).astype(np.float32)
            gt_normals = None
        else:
            gt_mesh = trimesh.load_mesh(gt_path)
            if isinstance(gt_mesh, trimesh.Trimesh):
                gt_pointcloud, idx = gt_mesh.sample(n_points, return_index=True)
                gt_pointcloud = gt_pointcloud.astype(np.float32)
                gt_normals = gt_mesh.face_normals[idx]
            elif isinstance(gt_mesh, trimesh.PointCloud):
                gt_pointcloud = gt_mesh.vertices.astype(np.float32)
                gt_normals = None
            else:
                raise RuntimeError('Unknown data type!')
        # normalize according to the scale of the gt point cloud
        if normalize:
            center = gt_pointcloud.mean(0)
            gt_scale = np.abs(gt_pointcloud-center).max()
            print('Normalize with scale: %.2f' % gt_scale)
        gt_pointcloud /= gt_scale
        gt_cache.update({gt_path: (gt_pointcloud, gt_normals, gt_scale)})

    scale = np.abs(gt_pointcloud).max()
    if normalize:
        es_mesh.vertices /= gt_scale
        scale = 1.
    thresholds=np.linspace(1./1000, 1, 1000) * scale # for F-Score calculation
    result=evaluator.eval_mesh(es_mesh, gt_pointcloud, gt_normals, thresholds=thresholds)
    return result
```

**Comment by Runsong123** [comment]
Great, I will try this. Thanks so much!!

BTW, I am curious about the SRB dataset, I found the data contains the normal. (I use your script to download the SRB data). But I saw you do not use the normal to calculate the Normal Metric. Is there any problem with the given normals?

**Comment by pengsongyou** [comment]
@Runsong123 I also checked the data but I don't think there is any normal provided in SRB (corresponding to deep_geometric_prior_data in the folder). Are you sure that you download it correctly with our script?

**Comment by Runsong123** [comment]
I use the [link](https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/data/optim_data.zip) provided in scripts/download_optim_data.sh. 

For example, I just open the "anchor.ply", I can see the following description:

```
ply
format binary_little_endian 1.0
element vertex 61460
property float x
property float y
property float z
property float nx
property float ny
property float nz
end_header
```


* I  found the file type belongs to the ("trimesh.PointCloud"). 
* Maybe it makes sense, cause the GT_point is sample from GT mesh. The file is just  point cloud with normals. (I guess)

**Comment by pengsongyou** [comment]
Ah you are right @Runsong123, there are indeed normals provided, so it is really our oversight. Nevertheless, after checking the data again, we also realize that there are some regions that are only partially or not scanned, so there are missing areas (like a hole). The normals for the boundaries of those regions might not be accurate, which might have a negative impact in the evaluation. Still, we should have evaluated the normal consistency on SRB as well. Thanks for pointing it out!

**Comment by Runsong123** [comment]
Got it :)
In addition, I am wondering whether the normal consistency corresponds to the "normals" item or others?

**Comment by Runsong123** [comment]
I have tried to calculate the metric for the metric, I found the F-score and Normal C. is similar to your result showed in paper, but the Chamfer_L1 is much lower than your paper. (e,g, My results: 0.04  VS your paper results: 0.44 )

**Comment by pengsongyou** [comment]
It is not just for IGR, but for all methods we scale the CD by 10x. Check out the [note for explanation](https://github.com/autonomousvision/convolutional_occupancy_networks#evaluation).

**Comment by Runsong123** [comment]
> It is not just for IGR, but for all methods we scale the CD by 10x. Check out the [note for explanation](https://github.com/autonomousvision/convolutional_occupancy_networks#evaluation).

Got it, Thanks for your quick reply.
Cause I am very interested in scene/object-specific neural reconstruction, I just want to compare the existing method. Thanks for your patience!

**Comment by Runsong123** [comment]
> It is not just for IGR, but for all methods we scale the CD by 10x. Check out the [note for explanation](https://github.com/autonomousvision/convolutional_occupancy_networks#evaluation). We were simply following this protocol, but actually it does not make too much sense for these datasets for optimization-based methods. Still, scale up 10x helps to better show the differences among different methods since 0.44 is more informative than 0.04 in my opinion.

Got it, Thanks for your quick reply.
Cause I am very interested in scene/object-specific neural reconstruction, I just want to compare the existing method. Thanks for your patience!
