### ISSUE TITLE
Fail to setup pytorch3d 0.6.0 : a typo?

### ISSUE THREAD

**Issue by xiazeqing** [autonomousvision/shape_as_points#7]
In section [Installation](https://github.com/autonomousvision/shape_as_points/blob/main/README.md#installation)
"
Now, you can install PyTorch3D 0.6.0 from the official instruction as follows
`
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html`
"
but I can only get pytorch3d 0.0.1 to 0.3.0 from the above address. I want to check whether we should install pytorch3d 0.3.0 with the above command or manually install pytorch 0.6.0 from official instruction?

P.S. I tried pytorch3d 0.3.0 but it ends up with 
`ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory`

Thanks!

**Comment by pengsongyou** [comment]
Hi @xiazeqing ,

When I released the code two months back, my instruction worked correctly to install PyTorch3D. However, PyTorch3D is updating all the time, now maybe it is not compatible again... I am not happy about it :\

To answer your question, please install Pytorch3D 0.6 manually from their instruction, since my code is not compatible with 0.3. Also, The error that you got was because you installed an non-CUDA version PyTorch3D. It is always a bit tricky to install PyTorch3D...

**Comment by adizhol** [comment]
I haven't worked with shape_as_points, but you cab try compiling pytorch2d
with pip install - check the documentation.

**Comment by jiangsijia9495** [comment]
@xiazeqing You can install latest pytorch3d by source followed the instruction on their official github website.

**Comment by xiazeqing** [comment]
> Hi @xiazeqing ,
> 
> When I released the code two months back, my instruction worked correctly to install PyTorch3D. However, PyTorch3D is updating all the time, now maybe it is not compatible again... I am not happy about it :\
> 
> To answer your question, please install Pytorch3D 0.6 manually from their instruction, since my code is not compatible with 0.3. Also, The error that you got was because you installed an non-CUDA version PyTorch3D. It is always a bit tricky to install PyTorch3D...

Thank you for answering, and I suggest to edit the readme and remove the script, just ask users to install from official github website. (And I am quite confused why 0.6.0 was available from pip before but they are not available for now, only 0.3.0 remaining.)
By the way, I tried pytorch3d 0.6.1 and it works fine.

For the second problem, my CUDA didn't work just because of old systems cannot handle CUDA 10.2 and I need to update OS first, and then NVIDIA driver, and finally install pytorch3d successfully. Hope this issue would be helpful for later users.

**Comment by pengsongyou** [comment]
@xiazeqing thanks for pointing out the issue. I have modified the readme accordingly.

**Comment by qixuema** [comment]
> > Hi @xiazeqing ,
> > When I released the code two months back, my instruction worked correctly to install PyTorch3D. However, PyTorch3D is updating all the time, now maybe it is not compatible again... I am not happy about it :\
> > To answer your question, please install Pytorch3D 0.6 manually from their instruction, since my code is not compatible with 0.3. Also, The error that you got was because you installed an non-CUDA version PyTorch3D. It is always a bit tricky to install PyTorch3D...
> 
> Thank you for answering, and I suggest to edit the readme and remove the script, just ask users to install from official github website. (And I am quite confused why 0.6.0 was available from pip before but they are not available for now, only 0.3.0 remaining.) By the way, I tried pytorch3d 0.6.1 and it works fine.
> 
> For the second problem, my CUDA didn't work just because of old systems cannot handle CUDA 10.2 and I need to update OS first, and then NVIDIA driver, and finally install pytorch3d successfully. Hope this issue would be helpful for later users.

Hi,
Thanks for your answering.
How can you install pytorch3d==0.6.1 with the CUDA==10.2 and pytorch==1.9.0?
