### ISSUE TITLE
question about interpolation method

### ISSUE THREAD

**Issue by l1346792580123** [autonomousvision/shape_as_points#8]
Thanks for sharing this great work! It seems that the interpolation method used in the point_rasterize and grid_interp function is based on the absolute distance of the point to the adjacent grid point. Have you ever tried other interpolation method such as trilinear interpolation? Do different interpolation methods affect the results?

**Comment by pengsongyou** [comment]
I guess you misunderstand our code. We are indeed doing the trilinear interpolation based on the distance to the adjacent grid points, as you can see: https://github.com/autonomousvision/shape_as_points/blob/main/src/utils.py#L101-L110. It is not nearest neighbor.

**Comment by l1346792580123** [comment]
Sorry for the misunderstanding. I am not familiar with the interpolation method. Are there any other common interpolation methods except trilinear interpolation? I want to try out the effect of different interpolation methods on the results.

**Comment by pengsongyou** [comment]
You can check Wikipedia https://en.wikipedia.org/wiki/Interpolation

We only consider trilinear interpolation here.
